// قور الخصومات
const List<String> imagecursl = [
  "assets/images/comm/a3laan.png",
  "assets/images/comm/banner2.jpg",
  "assets/images/comm/a3laan.png",
  "assets/images/comm/banner2.jpg",
  "assets/images/comm/a3laan.png",
];
const List<String> categoryimage = [
  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",
];
const List<String> categoryimage22 = [
  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",
    "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",
    "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",
    "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",
    "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",
    "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",
    "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",
    "assets/images/category/a.png",
      "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",
    "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",
    "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",
    "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",
    "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",
    "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",

    "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",
  
    "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",
  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",

    "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",
  "assets/images/category/a.png",
  "assets/images/category/a2.png",
  "assets/images/category/a3.png",
  "assets/images/category/aa.png",
  "assets/images/category/download.jfif",
  "assets/images/category/images.jfif",

];
const List<String> productimages = [
  'assets/images/product/prod1.png',
  'assets/images/product/image69.png',
  'assets/images/product/image100.png',
  'assets/images/product/image103.png',
  'assets/images/product/image104.png',
];
const List<String> productdetailsimages = [
  'assets/images/product/prod1.png',
  'assets/images/product/t1.webp',
  'assets/images/product/t2.webp',
];
